---
application: CarFreeAtoZ
name: CarFreeAtoZ
domain: arlington.conveyal.com

organization:
  name: Arlington County Commuter Services
  url: https://www.commuterdirect.com/

# Application
version: 0.5.0

# Support Email Address
email:
  name: Trevor Gerhardt
  address: tgerhardt@conveyal.com

# Geocoding
geocode:
  bbox: -78,38,-76,40
  center: -77.105933,38.880148

# Default application values
api_url: /api
base_url: http://localhost:5000
mapbox_map_id: conveyal.ie3o67m0
otp:
  host: localhost
  path: /otp/routers/default
  port: 8080
s3_bucket: ''
segmentio_key: ''
static_url: ''

# Custom Environments
environments:

  # For running tests
  test:

  # Default & development
  development:
    segmentio_key: egulwcylaa

  # Staging / QA
  staging:
    base_url: http://arlington.dev.conveyal.com
    opsworks:
      app_id: 1d2d64dd-5ee0-4867-823b-6072e92e297d
    s3_bucket: s3://carfreeatoz-staging/
    segmentio_key: qak98wes8c
    static_url: https://s3.amazonaws.com/carfreeatoz-staging

  # Production envrionment
  production:
    base_url: http://carfreeatoz.com
    opsworks:
      app_id: e6d503e7-2ded-49df-a62b-8ac2c000b963
    otp:
      host: ec2-54-234-252-174.compute-1.amazonaws.com
      path: /otp/routers/default
      port: 80
    s3_bucket: s3://carfreeatoz/
    segmentio_key: 51cp2qlgkb
    static_url: https://s3.amazonaws.com/carfreeatoz

