---
application: CarFreeAtoZ
name: CarFreeAtoZ
domain: conveyal.com
organization: Arlington County Commuter Services

# Application
version: 0.5.0

# Support Email Address
email:
  name: Trevor Gerhardt
  address: tgerhardt@conveyal.com

# Default application values
api_url: /api
base_url: http://localhost:5000
mapbox_map_id: conveyal.ie3o67m0
otp:
  host: ec2-23-21-67-127.compute-1.amazonaws.com
  path: /otp/routers/default
  port: 80
s3_bucket: ''
segmentio_key: ''
static_url: ''

# Custom Environments
environments:

  # For running tests
  test:

  # Default & development
  development:
    segmentio_key: egulwcylaa

  # Staging / QA
  staging:
    base_url: http://arlington.dev.conveyal.com
    s3_bucket: arlington.dev.conveyal.com
    segmentio_key: qak98wes8c
    static_url: https://s3.amazonaws.com/arlington.dev.conveyal.com

  # Production envrionment
  production:
    base_url: http://arlington.conveyal.com
    otp:
      host: ec2-54-234-252-174.compute-1.amazonaws.com
      path: /otp/routers/default
      port: 80
    s3_bucket: arlington.conveyal.com
    segmentio_key: 51cp2qlgkb
    static_url: https://s3.amazonaws.com/arlington.conveyal.com

